---
- name: Check collection from hub
  hosts: localhost
  gather_facts: false
  tasks:
    - name: get some info
      amazon.aws.ec2_vpc_net_info: null
      region: "{{ ec2_region }}"
      register: all_the_info
      connection: local
      delegate_to: localhost
      run_once: true
    - name: how many vpc?
      debug:
        msg: There are {{ all_the_info.vpcs|length }} VPCs
