---
- name: get some info
  ec2_vpc_net_info:
    region: "{{ ec2_region }}"
  register: all_the_info
  connection: local
  delegate_to: localhost
  run_once: true
- name: how many vpc?
  debug:
    msg: "There are {{ all_the_info.vpcs|length }} VPCs"
