---
- name: Check collection from hub
  hosts: localhost
  become: true
  gather_facts: false
  tasks:
    - name: get some info
      amazon.aws.ec2_vpc_net_info:
        region: "ap-south-1"
      register: all_the_info
      connection: local
      delegate_to: localhost
      run_once: true
      
    - name: how many vpc?
      debug:
        msg: "There are {{ all_the_info.vpcs|length }} VPCs"
