---
- name: Check collection from hub
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Gather information about active zones
      ansible.posix.firewalld_info:
        active_zones: true

- name: Gather information about specific zones
  ansible.posix.firewalld_info:
    zones:
      - public
      - external
      - internal

